sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: deps="high"

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - if [ "$deps" = "high" ]; then composer config minimum-stability dev; fi
  - composer update $COMPOSER_FLAGS

script:
  - php validate.php
