sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
    - php: 7.2
      env: deps="high"

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - if [ "$deps" = "high" ]; then composer config minimum-stability dev; fi
  - composer update $COMPOSER_FLAGS

script:
  - php validate.php
